"""Create initial tables: items, products, users

Revision ID: 001
Revises:
Create Date: 2024-01-01 00:00:00

TOPIC: Alembic Migrations

This file was AUTO-GENERATED by:
    alembic revision --autogenerate -m "Create initial tables"

Then APPLIED to the DB by:
    alembic upgrade head

To UNDO this migration:
    alembic downgrade -1
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create all tables."""

    # ── items table ───────────────────────────────────────────
    op.create_table(
        "items",
        sa.Column("id",         sa.Integer(),    nullable=False),
        sa.Column("name",       sa.String(100),  nullable=False),
        sa.Column("price",      sa.Float(),      nullable=False),
        sa.Column("created_at", sa.DateTime(),   server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(),   nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_items_id", "items", ["id"])

    # ── products table ────────────────────────────────────────
    op.create_table(
        "products",
        sa.Column("id",          sa.Integer(),   nullable=False),
        sa.Column("name",        sa.String(100), nullable=False),
        sa.Column("sku",         sa.String(50),  nullable=False),
        sa.Column("price",       sa.Float(),     nullable=False),
        sa.Column("stock",       sa.Integer(),   server_default="0"),
        sa.Column("description", sa.Text(),      nullable=True),
        sa.Column("created_at",  sa.DateTime(),  server_default=sa.func.now()),
        sa.Column("updated_at",  sa.DateTime(),  nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku"),
    )
    op.create_index("ix_products_id",  "products", ["id"])
    op.create_index("ix_products_sku", "products", ["sku"])

    # ── users table ───────────────────────────────────────────
    op.create_table(
        "users",
        sa.Column("id",         sa.Integer(),   nullable=False),
        sa.Column("username",   sa.String(50),  nullable=False),
        sa.Column("email",      sa.String(100), nullable=False),
        sa.Column("is_active",  sa.Boolean(),   server_default="true"),
        sa.Column("created_at", sa.DateTime(),  server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(),  nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_users_id",       "users", ["id"])
    op.create_index("ix_users_username", "users", ["username"])
    op.create_index("ix_users_email",    "users", ["email"])


def downgrade() -> None:
    """Drop all tables (undo this migration)."""
    op.drop_table("users")
    op.drop_table("products")
    op.drop_table("items")
